name: 🚚 ADO Repo Migration Request
description: Migrate a repository (and optionally pipelines) from Azure DevOps to GitHub.
title: "[Migration]: <ADO Repo Name>"
labels: [automation, migration]
body:
  - type: input
    id: ado_org
    attributes:
      label: Azure DevOps Organization
      placeholder: e.g., myadoorg
    validations:
      required: true

  - type: input
    id: ado_project
    attributes:
      label: Azure DevOps Project
      placeholder: e.g., MyProject
    validations:
      required: true

  - type: input
    id: ado_repo
    attributes:
      label: Azure DevOps Repo Name
      placeholder: e.g., LegacyApp
    validations:
      required: true

  - type: input
    id: gh_repo
    attributes:
      label: Target GitHub Repo Name
      placeholder: e.g., migrated-legacy-app
    validations:
      required: true

  - type: input
    id: gh_org
    attributes:
      label: Target GitHub Org Name
      placeholder: e.g., migrated-legacy-app
    validations:
      required: true


  - type: dropdown
    id: include_pipelines
    attributes:
      label: Migrate Pipelines?
      description: Do you want to include Azure Pipelines in the migration?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: pipeline_id
    attributes:
      label: Pipeline ID
      description: Required *only if* pipeline migration is "Yes"
      placeholder: e.g., migrated-legacy-app
    validations:
      required: false
