name: Deploy extract-into-sheets

on:
  push:
    branches:
      - test
    paths:
      - 'functions/extract-into-sheets*/**'
      - '.github/workflows/deploy-extract-into-sheets.yml'
      - '.github/actions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCP with secret key
        uses: ./.github/actions/setup-gcp
        with:
          key: ${{ secrets.DB_PASSWORD }}

      - name: Deploy function (example step)
        run: echo "Deploying function with env"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
