name: Deploy extract-into-sheets

on:
  push:
    branches:
      - test
    paths:
      - 'functions/extract-into-sheets*/**'
      - '.github/workflows/deploy-extract-into-sheets.yml'
      - '.github/actions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCP with ***REMOVED*** key
        uses: ./.github/actions/setup-gcp
        with:
          key: ${{ ***REMOVED***s.***REMOVED*** }}

      - name: Deploy function (example step)
        run: echo "Deploying function with env"
        env:
          ***REMOVED***: ${{ ***REMOVED***s.***REMOVED*** }}
          DOCKER_PASSWORD: ${{ ***REMOVED***s.DOCKER_PASSWORD }}
