name: Deploy extract-into-sheets

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate hardcoded ***REMOVED***s (⚠️ bad practice)
        run: |
          echo "Hardcoded AWS key: AKIAIOSFOE"
          echo "Hardcoded AWS ***REMOVED***: wJalrXUtnFEMXAMPLEKEY"
          echo "Hardcoded GitHub ***REMOVED***: REDACTED_SECRET"
          echo "Hardcoded DB ***REMOVED***: REDACTED_SECRET!"

      - name: Deploy (placeholder)
        run: echo "Deploying app..."
