name: Deploy extract-into-sheets

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate hardcoded secrets (⚠️ bad practice)
        run: |
          echo "Hardcoded AWS key: AKIAIOSFOE"
          echo "Hardcoded AWS secret: wJalrXUtnFEMXAMPLEKEY"
          echo "Hardcoded GitHub token: ghp_exampleGithubTok7890"
          echo "Hardcoded DB ***REMOVED*** ***REMOVED***t123!"

      - name: Deploy (placeholder)
        run: echo "Deploying app..."
