name: 🚚 GitHub Secret Removal
description: This is a destructive process. Do you want to continue? Ensure you have a backup of your repository in case anything breaks during the operation.
title: "[Secret-Removal]: <GitHub Repo Name>"
labels: [automation]
body:
  - type: input
    id: gh_repo
    attributes:
      label: Target GitHub Repo Name
      placeholder: e.g., migrated-legacy-app
    validations:
      required: true

  - type: input
    id: gh_org
    attributes:
      label: Target GitHub Org Name
      placeholder: e.g., migrated-legacy-app
    validations:
      required: true


  - type: dropdown
    id: include_pipelines
    attributes:
      label: Secret Removal Pipelines?
      description: Do you want to continue?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

